#!/usr/bin/env bash
# Build this app and install it on a physical iPad/iPhone over USB or Wi-Fi.
#
#   scripts/install-device.sh                 # every eligible paired device
#   scripts/install-device.sh Echo            # devices whose name matches "Echo"
#   scripts/install-device.sh 00008132-...    # one device by UDID
#
# Unlike deploy-testflight.sh this signs with the team's *development*
# certificate, not the distribution one: the build goes straight onto a device
# that is registered on the team, with no App Store Connect round trip and no
# Beta App Review.
#
# A device has to be paired with Developer Mode on before it can take a build.
# For a new iPad, once:
#   1. Plug it into this Mac and unlock it; tap Trust, enter the passcode.
#      The Trust prompt only shows on an unlocked screen -- replug if missed.
#   2. Settings > Privacy & Security > Developer Mode > On, then restart.
#      The row is hidden until step 1 has happened at least once.
#   3. After the reboot, confirm the "Turn on Developer Mode?" alert. The
#      pre-reboot toggle only stages it; this alert is what enables it.
#   4. Register the device on the team (App Store Connect > Devices, or the
#      API). Signing fails with an opaque error until the UDID is on the team.
# After that first cable session the device can be reached over Wi-Fi.
#
# Development profiles expire a year after they are issued, at which point the
# app stops launching until it is rebuilt and reinstalled.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

die() { printf 'install-device: %s\n' "$*" >&2; exit 1; }
say() { printf '\033[1m==>\033[0m %s\n' "$*"; }

# --- credentials -----------------------------------------------------------
# Only the key *identifiers* are needed here; the private key itself stays in
# ~/.appstoreconnect. Every app on the team shares one key, so a repo without
# its own .deploy.env can borrow a sibling's rather than keep a second copy.
for cand in "$REPO/.deploy.env" "$REPO/ios/.deploy.env" \
            "$HOME/Documents/Code/pitchscope/.deploy.env"; do
  if [[ -f $cand ]]; then set -a; . "$cand"; set +a; break; fi
done
: "${ASC_KEY_ID:?set ASC_KEY_ID (or provide a .deploy.env)}"
: "${ASC_ISSUER_ID:?set ASC_ISSUER_ID (or provide a .deploy.env)}"
ASC_KEY_PATH="${ASC_KEY_PATH:-$HOME/.appstoreconnect/private_keys/AuthKey_${ASC_KEY_ID}.p8}"
[[ -f $ASC_KEY_PATH ]] || die "no App Store Connect key at $ASC_KEY_PATH"

# --- pick the devices ------------------------------------------------------
# Eligible means paired AND Developer Mode enabled; anything else cannot take
# a development build, and devicectl's error for that case is opaque.
DEVJSON="$(mktemp)"; trap 'rm -f "$DEVJSON"' EXIT
xcrun devicectl list devices --json-output "$DEVJSON" >/dev/null 2>&1 \
  || die "devicectl could not list devices"

# bash 3.2 is what macOS ships, so no mapfile.
DEVICES=()
while IFS= read -r _line; do
  [ -n "$_line" ] && DEVICES+=("$_line")
done < <(
  FILTER="${1:-}" python3 - "$DEVJSON" <<'PY'
import json, os, sys
want = os.environ.get("FILTER", "").strip().lower()
for d in json.load(open(sys.argv[1]))["result"]["devices"]:
    props = d.get("connectionProperties", {})
    caps = d.get("deviceProperties", {})
    name = caps.get("name", "?")
    udid = d.get("hardwareProperties", {}).get("udid", "")
    if props.get("pairingState") != "paired":
        continue
    if caps.get("developerModeStatus") != "enabled":
        continue
    if want and want not in name.lower() and want != udid.lower():
        continue
    print(f"{udid}\t{name}")
PY
)
[[ ${#DEVICES[@]} -gt 0 ]] || die "no paired device with Developer Mode enabled${1:+ matching '$1'}"

# --- build -----------------------------------------------------------------
# Two project shapes live across these repos: XcodeGen-generated native apps,
# and Quasar apps whose Xcode project is generated by Capacitor. Both end at an
# .app built for arm64 device, so only the front half differs.
DEST_ID="${DEVICES[0]%%$'\t'*}"
DERIVED="${DERIVED_DATA:-$REPO/.build/device}"

if [[ -f $REPO/frontend/src-capacitor/ios/App/App.xcworkspace/contents.xcworkspacedata ]]; then
  say "building the web app and syncing it into the Xcode project"
  # CocoaPods aborts on a non-UTF-8 locale, and its own crash reporter then
  # fails to render the real error -- so force the locale rather than debug
  # an Encoding::CompatibilityError that is never the actual problem.
  ( cd "$REPO/frontend" \
    && LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 npx quasar build -m capacitor -T ios --skip-pkg )
  XCARGS=(-workspace "$REPO/frontend/src-capacitor/ios/App/App.xcworkspace" -scheme App)
elif [[ -f $REPO/project.yml || -f $REPO/ios/project.yml ]]; then
  GENDIR="$REPO"; [[ -f $REPO/ios/project.yml ]] && GENDIR="$REPO/ios"
  say "regenerating the Xcode project from project.yml"
  # The .xcodeproj is gitignored build output; a new source file is invisible
  # to xcodebuild until XcodeGen has globbed it back in.
  ( cd "$GENDIR" && xcodegen generate >/dev/null )
  PROJ="$(find "$GENDIR" -maxdepth 1 -name '*.xcodeproj' | head -1)"
  [[ -n $PROJ ]] || die "no .xcodeproj after xcodegen in $GENDIR"
  XCARGS=(-project "$PROJ" -scheme "$(basename "$PROJ" .xcodeproj)")
else
  die "cannot tell what kind of project this is (no project.yml, no Capacitor workspace)"
fi

say "building for device"
xcodebuild "${XCARGS[@]}" \
  -configuration "${CONFIGURATION:-Debug}" \
  -destination "id=$DEST_ID" \
  -derivedDataPath "$DERIVED" \
  -allowProvisioningUpdates \
  -authenticationKeyPath "$ASC_KEY_PATH" \
  -authenticationKeyID "$ASC_KEY_ID" \
  -authenticationKeyIssuerID "$ASC_ISSUER_ID" \
  build

APP="$(find "$DERIVED/Build/Products" -maxdepth 2 -name '*.app' -path '*-iphoneos/*' | head -1)"
[[ -n $APP ]] || die "the build produced no .app under $DERIVED"

# --- install ---------------------------------------------------------------
for entry in "${DEVICES[@]}"; do
  udid="${entry%%$'\t'*}"; name="${entry#*$'\t'}"
  say "installing $(basename "$APP") on $name"
  xcrun devicectl device install app --device "$udid" "$APP" >/dev/null
done

say "done: $(basename "$APP") on ${#DEVICES[@]} device(s)"
