"""Deterministic score operations on music21 streams.

These are the "hands" of the arrangement agent: the LLM decides *what* to do,
these functions do it exactly. No notation is ever generated by a model.
"""

import copy

from music21 import chord as m21chord
from music21 import clef as m21clef
from music21 import instrument as m21instrument
from music21 import interval as m21interval
from music21 import note as m21note
from music21 import pitch as m21pitch
from music21 import stream

CLEFS = {
    "treble": m21clef.TrebleClef,
    "bass": m21clef.BassClef,
    "alto": m21clef.AltoClef,
    "tenor": m21clef.TenorClef,
    "treble8vb": m21clef.Treble8vbClef,
    "bass8vb": m21clef.Bass8vbClef,
    "percussion": m21clef.PercussionClef,
}

# Practical sounding (concert-pitch) ranges, keyed by music21 instrument class name.
RANGES = {
    "Violin": ("G3", "A7"),
    "Viola": ("C3", "E6"),
    "Violoncello": ("C2", "C6"),
    "Contrabass": ("E1", "G4"),
    "Flute": ("C4", "D7"),
    "Piccolo": ("D5", "C8"),
    "Oboe": ("B-3", "A6"),
    "EnglishHorn": ("E3", "C6"),
    "Clarinet": ("D3", "B-6"),
    "BassClarinet": ("B-1", "G5"),
    "Bassoon": ("B-1", "E-5"),
    "Horn": ("B1", "F5"),
    "Trumpet": ("F#3", "D6"),
    "Trombone": ("E2", "F5"),
    "Tuba": ("D1", "F4"),
    "Piano": ("A0", "C8"),
    "Harp": ("C1", "G7"),
    "Guitar": ("E2", "B5"),
    "Soprano": ("C4", "C6"),
    "Alto": ("F3", "F5"),
    "Tenor": ("C3", "C5"),
    "Bass": ("E2", "E4"),
}

DEFAULT_CLEF = {
    "Viola": "alto",
    "Violoncello": "bass",
    "Contrabass": "bass",
    "Bassoon": "bass",
    "Trombone": "bass",
    "Tuba": "bass",
    "BassClarinet": "bass",
    "Horn": "treble",
    "Tenor": "treble8vb",
    "Bass": "bass",
    "Guitar": "treble8vb",
    "Contrabassoon": "bass",
    "Timpani": "bass",
}


def part_label(p) -> str:
    return p.partName or (p.id if isinstance(p.id, str) else "Part")


def list_part_labels(score) -> list[str]:
    return [part_label(p) for p in score.parts]


def find_parts(score, names: list[str]):
    """Match parts by name (case-insensitive, exact then substring) or by index ('#0', '#1', ...)."""
    matched = []
    all_parts = list(score.parts)
    for name in names:
        want = name.strip().lower()
        if want.startswith("#"):
            try:
                idx = int(want[1:])
                hits = [all_parts[idx]]
            except (ValueError, IndexError):
                raise ValueError(f"Bad part index '{name}'. Score has {len(all_parts)} parts (#0..#{len(all_parts) - 1})")
            for p in hits:
                if p not in matched:
                    matched.append(p)
            continue
        exact = [p for p in score.parts
                 if (p.partName or "").lower() == want
                 or (p.partAbbreviation or "").lower() == want
                 or (isinstance(p.id, str) and p.id.lower() == want)]
        hits = exact or [p for p in score.parts if want in (p.partName or "").lower()]
        if not hits:
            raise ValueError(f"No part matches '{name}'. Available parts: {list_part_labels(score)}")
        for p in hits:
            if p not in matched:
                matched.append(p)
    return matched


def rename_part(part, new_name: str, abbreviation: str | None = None) -> dict:
    old = part_label(part)
    part.partName = new_name
    if abbreviation:
        part.partAbbreviation = abbreviation
    return {"from": old, "to": new_name}


def keep_parts(score, names: list[str]) -> list[str]:
    matched = find_parts(score, names)
    removed = []
    for p in list(score.parts):
        if p not in matched:
            removed.append(part_label(p))
            score.remove(p, recurse=True)
    return removed


def remove_parts(score, names: list[str]) -> list[str]:
    matched = find_parts(score, names)
    if len(matched) == len(list(score.parts)):
        raise ValueError("Refusing to remove every part in the score.")
    removed = []
    for p in matched:
        removed.append(part_label(p))
        score.remove(p, recurse=True)
    return removed


def merge_parts(score, names: list[str], new_name: str, clef_name: str = "treble") -> dict:
    """Merge several parts into one staff, each source part becoming its own voice.

    Lossless: every note, rest, and duration of every source part is preserved
    (measure by measure, as independent voices on the shared staff). The merged
    part takes the place of the first source part in score order.
    """
    if clef_name not in CLEFS:
        raise ValueError(f"Unknown clef '{clef_name}'. Choose from: {sorted(CLEFS)}")
    sources = find_parts(score, names)
    if len(sources) < 2:
        raise ValueError("merge-parts needs at least two distinct parts")

    note_total = sum(1 for p in sources for n in p.recurse().notes for _ in n.pitches)
    measures_by_part = [list(p.getElementsByClass(stream.Measure)) for p in sources]
    n_measures = max(len(ms) for ms in measures_by_part)

    merged = stream.Part()
    merged.partName = new_name
    merged.partAbbreviation = new_name

    for idx in range(n_measures):
        ref = next((ms[idx] for ms in measures_by_part if idx < len(ms)), None)
        m_new = stream.Measure(number=ref.number if ref is not None else idx + 1)
        if idx == 0:
            m_new.insert(0.0, CLEFS[clef_name]())
        for kind in ("TimeSignature", "KeySignature"):
            for el in ref.getElementsByClass(kind):
                m_new.insert(el.offset, copy.deepcopy(el))
        for vi, ms in enumerate(measures_by_part):
            if idx >= len(ms):
                continue
            voice = stream.Voice(id=str(vi + 1))
            for el in ms[idx].notesAndRests:
                voice.insert(el.offset, copy.deepcopy(el))
            m_new.insert(0.0, voice)
        merged.append(m_new)

    labels = [part_label(p) for p in sources]
    score.replace(sources[0], merged)
    for p in sources[1:]:
        score.remove(p, recurse=True)

    merged_total = sum(1 for n in merged.recurse().notes for _ in n.pitches)
    if merged_total != note_total:
        raise RuntimeError(f"Note-count mismatch after merge: sources had {note_total}, merged has {merged_total}")
    return {"merged": labels, "into": new_name, "clef": clef_name,
            "voices": len(sources), "notes_before": note_total, "notes_after": merged_total}


def split_bass(score, name: str, bass_name: str, chords_name: str,
               instrument_name: str | None = None) -> dict:
    """Split one part into a bass staff and a chords staff.

    The source part is chordified into time slices. At every slice the lowest
    sounding pitch goes to the bass staff (bass clef); all remaining pitches
    become a chord on the chords staff (treble clef). The chords staff replaces
    the source part in score order; the bass staff is appended below it.
    """
    src = find_parts(score, [name])[0]
    sliced = src.chordify(addTies=True)

    bass_part = stream.Part()
    bass_part.partName = bass_name
    bass_part.partAbbreviation = bass_name
    chords_part = stream.Part()
    chords_part.partName = chords_name
    chords_part.partAbbreviation = chords_name

    slice_pitches = 0
    bass_notes = 0
    chord_notes = 0

    for m in sliced.getElementsByClass(stream.Measure):
        mb = stream.Measure(number=m.number)
        mc = stream.Measure(number=m.number)
        if m.number <= 1 and m is sliced.getElementsByClass(stream.Measure).first():
            mb.insert(0.0, m21clef.BassClef())
            mc.insert(0.0, m21clef.TrebleClef())
        for kind in ("TimeSignature", "KeySignature"):
            for el in m.getElementsByClass(kind):
                mb.insert(el.offset, copy.deepcopy(el))
                mc.insert(el.offset, copy.deepcopy(el))
        for el in m.notesAndRests:
            off, dur = el.offset, el.quarterLength
            if el.isRest or not el.pitches:
                mb.insert(off, m21note.Rest(quarterLength=dur))
                mc.insert(off, m21note.Rest(quarterLength=dur))
                continue
            pitches = sorted(el.pitches, key=lambda p: p.ps)
            slice_pitches += len(pitches)

            b = m21note.Note(pitches[0])
            b.quarterLength = dur
            if el.tie is not None:
                b.tie = copy.deepcopy(el.tie)
            mb.insert(off, b)
            bass_notes += 1

            upper = pitches[1:]
            if upper:
                c = m21note.Note(upper[0]) if len(upper) == 1 else m21chord.Chord(upper)
                c.quarterLength = dur
                if el.tie is not None:
                    c.tie = copy.deepcopy(el.tie)
                mc.insert(off, c)
                chord_notes += len(upper)
            else:
                mc.insert(off, m21note.Rest(quarterLength=dur))
        bass_part.append(mb)
        chords_part.append(mc)

    if bass_notes + chord_notes != slice_pitches:
        raise RuntimeError(f"Split lost pitches: {slice_pitches} sliced vs {bass_notes + chord_notes} placed")

    if instrument_name:
        for p in (bass_part, chords_part):
            p.insert(0.0, m21instrument.fromString(instrument_name))

    old_label = part_label(src)
    score.replace(src, chords_part)
    score.insert(0.0, bass_part)  # same offset, inserted last -> bottom staff

    return {"split": old_label, "chords_staff": chords_name, "bass_staff": bass_name,
            "slices": bass_notes, "bass_notes": bass_notes, "chord_notes": chord_notes,
            "note": "sustained notes are sliced at each attack (tied where the source was tied)"}


def consolidate_ties(score, names: list[str]) -> list[dict]:
    """Merge runs of tied same-pitch notes into single notes of combined duration.

    A quarter tied to a half becomes a dotted half; notes genuinely spanning a
    barline get re-tied at the barline on export. Pitch content and total
    durations are unchanged — this is purely notational cleanup.
    """
    report = []
    for p in find_parts(score, names):
        before = len(list(p.recurse().notes))
        p.stripTies(inPlace=True, matchByPitch=True)
        after = len(list(p.recurse().notes))
        report.append({"part": part_label(p), "events_before": before,
                       "events_after": after, "merged": before - after})
    return report


def limit_part(score, name: str, max_pitch: str | None = None, monophonic: bool = False) -> dict:
    """Enforce playability constraints on a part, always sacrificing higher notes.

    --monophonic: chords are reduced to their lowest note; where two notes
    overlap in time, the higher one is removed.
    --max-pitch: notes strictly above this pitch are removed (replaced by
    rests); chords keep only their pitches at or below it.
    """
    part = find_parts(score, [name])[0]
    maxp = m21pitch.Pitch(max_pitch) if max_pitch else None
    stats = {"part": part_label(part), "chords_reduced": 0, "overlaps_removed": 0, "high_removed": 0}

    for m in part.getElementsByClass(stream.Measure):
        containers = list(m.voices) or [m]
        for cont in containers:
            if monophonic:
                for el in list(cont.notes):
                    if el.isChord:
                        lo = min(el.pitches, key=lambda x: x.ps)
                        n = m21note.Note(lo)
                        n.quarterLength = el.quarterLength
                        if el.tie is not None:
                            n.tie = copy.deepcopy(el.tie)
                        cont.replace(el, n)
                        stats["chords_reduced"] += 1
                kept = []
                for el in sorted(cont.notes, key=lambda e: e.offset):
                    dropped = False
                    while kept and el.offset < kept[-1].offset + kept[-1].quarterLength - 1e-6:
                        prev = kept[-1]
                        if min(p.ps for p in el.pitches) < min(p.ps for p in prev.pitches):
                            cont.remove(prev)
                            kept.pop()
                            stats["overlaps_removed"] += 1
                        else:
                            cont.remove(el)
                            stats["overlaps_removed"] += 1
                            dropped = True
                            break
                    if not dropped:
                        kept.append(el)
            if maxp is not None:
                for el in list(cont.notes):
                    keep = [x for x in el.pitches if x.ps <= maxp.ps]
                    if len(keep) == len(el.pitches):
                        continue
                    stats["high_removed"] += len(el.pitches) - len(keep)
                    if keep:
                        n = m21note.Note(keep[0]) if len(keep) == 1 else m21chord.Chord(keep)
                        n.quarterLength = el.quarterLength
                        if el.tie is not None:
                            n.tie = copy.deepcopy(el.tie)
                        cont.replace(el, n)
                    else:
                        cont.replace(el, m21note.Rest(quarterLength=el.quarterLength))
    if maxp is not None:
        stats["max_pitch"] = maxp.nameWithOctave
    return stats


def transpose(score, interval_str: str, names: list[str] | None = None) -> dict:
    itv = m21interval.Interval(interval_str)
    if names:
        targets = find_parts(score, names)
        for p in targets:
            p.transpose(itv, inPlace=True)
        scope = [part_label(p) for p in targets]
    else:
        score.transpose(itv, inPlace=True)
        scope = "all parts"
    return {"interval": itv.niceName, "direction": itv.direction.name.lower(), "scope": scope}


def change_clef(part, clef_name: str, from_measure: int = 1) -> dict:
    if clef_name not in CLEFS:
        raise ValueError(f"Unknown clef '{clef_name}'. Choose from: {sorted(CLEFS)}")
    measures = list(part.getElementsByClass(stream.Measure))
    if not measures:
        raise ValueError("Part has no measures")
    target = next((m for m in measures if m.number == from_measure), None)
    if target is None:
        if from_measure <= 1:
            target = measures[0]
        else:
            raise ValueError(f"No measure {from_measure} (part has {len(measures)} measures)")
    for old in list(target.getElementsByClass(m21clef.Clef)):
        target.remove(old)
    target.insert(0.0, CLEFS[clef_name]())
    return {"part": part_label(part), "clef": clef_name, "from_measure": target.number}


def range_violations(part, class_name: str) -> list[dict]:
    lo, hi = (m21pitch.Pitch(x) for x in RANGES[class_name])
    out = []
    for n in part.recurse().notes:
        for p in n.pitches:
            if p < lo or p > hi:
                out.append({"measure": n.measureNumber, "pitch": p.nameWithOctave})
    return out


def change_instrument(part, target_name: str) -> dict:
    """Swap a part's instrument idiomatically.

    Works in sounding pitch, octave-shifts the whole line to best fit the new
    instrument's range, sets the idiomatic clef, then converts to written pitch
    for transposing instruments. Reports what it did and what still needs a
    human ear (remaining out-of-range notes).
    """
    new_instr = m21instrument.fromString(target_name)
    cls = type(new_instr).__name__
    if cls == "Instrument":
        raise ValueError(f"Unrecognized instrument '{target_name}'")

    try:
        part.toSoundingPitch(inPlace=True)
    except Exception:
        pass
    part.atSoundingPitch = True

    old_label = part_label(part)
    for old in list(part.recurse().getElementsByClass(m21instrument.Instrument)):
        part.remove(old, recurse=True)
    part.insert(0.0, new_instr)
    part.partName = new_instr.instrumentName or target_name
    part.partAbbreviation = new_instr.instrumentAbbreviation or part.partName

    report = {"from": old_label, "to": part.partName, "octave_shift": 0, "out_of_range": []}

    if cls in RANGES:
        lo, hi = (m21pitch.Pitch(x).ps for x in RANGES[cls])
        ps_vals = [p.ps for n in part.recurse().notes for p in n.pitches]
        if ps_vals:
            def violations_at(shift: int) -> int:
                return sum(1 for v in ps_vals if not (lo <= v + 12 * shift <= hi))
            best = min((0, -1, 1, -2, 2), key=lambda s: (violations_at(s), abs(s)))
            if best != 0 and violations_at(best) < violations_at(0):
                part.transpose(m21interval.Interval(12 * best), inPlace=True)
                report["octave_shift"] = best
            report["out_of_range"] = range_violations(part, cls)

    clef_name = DEFAULT_CLEF.get(cls, "treble")
    change_clef(part, clef_name, 1)
    report["clef"] = clef_name

    if new_instr.transposition is not None:
        try:
            part.toWrittenPitch(inPlace=True)
            report["written_transposition"] = new_instr.transposition.niceName
        except Exception:
            report["written_transposition"] = "FAILED — part left at concert pitch"
    return report


FLAT_NAMES = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"]

CHORD_TEMPLATES = [
    ("", {0, 4, 7}),          # major
    ("m", {0, 3, 7}),         # minor
    ("7", {0, 4, 7, 10}),     # dominant 7th
    ("m7", {0, 3, 7, 10}),
    ("maj7", {0, 4, 7, 11}),
    ("m7b5", {0, 3, 6, 10}),
    ("6", {0, 4, 7, 9}),
    ("m6", {0, 3, 7, 9}),
    ("dim", {0, 3, 6}),
    ("dim7", {0, 3, 6, 9}),
    ("aug", {0, 4, 8}),
]

QUALITY_KINDS = {
    "": "major", "m": "minor", "7": "dominant-seventh", "m7": "minor-seventh",
    "maj7": "major-seventh", "m7b5": "half-diminished-seventh",
    "6": "major-sixth", "m6": "minor-sixth",
    "dim": "diminished", "dim7": "diminished-seventh", "aug": "augmented",
}


def analyze_harmony(score, names: list[str] | None = None) -> dict:
    """Per-measure harmony extraction (read-only).

    For each measure, every sounding pitch class is weighted by duration and
    matched against chord templates over all 12 roots; the bass note at the
    downbeat weighs in favor of root-position readings. Returns ranked
    candidates per bar — the *judgment* of which label is musically right
    stays with the caller (the agent), by design.
    """
    parts = find_parts(score, names) if names else list(score.parts)
    measures_by_part = [list(p.getElementsByClass(stream.Measure)) for p in parts]
    n_measures = max(len(ms) for ms in measures_by_part)
    try:
        global_key = str(score.analyze("key"))
    except Exception:
        global_key = None

    out = []
    for i in range(n_measures):
        weights: dict[int, float] = {}
        bass_pc, bass_ps = None, None
        for ms in measures_by_part:
            if i >= len(ms):
                continue
            for el in ms[i].recurse().notes:
                w = float(el.quarterLength) or 0.25
                for pt in el.pitches:
                    weights[pt.pitchClass] = weights.get(pt.pitchClass, 0.0) + w
                    if el.offset < 0.75 and (bass_ps is None or pt.ps < bass_ps):
                        bass_ps, bass_pc = pt.ps, pt.pitchClass
        number = next((ms[i].number for ms in measures_by_part if i < len(ms)), i + 1)
        if not weights:
            out.append({"measure": number, "bass": None, "top": []})
            continue
        total = sum(weights.values())
        cands = []
        for root in range(12):
            for suffix, tpl in CHORD_TEMPLATES:
                tpl_pcs = {(root + iv) % 12 for iv in tpl}
                in_w = sum(w for pc, w in weights.items() if pc in tpl_pcs)
                coverage = sum(1 for pc in tpl_pcs if weights.get(pc, 0) > 0) / len(tpl_pcs)
                third = (root + (3 if suffix.startswith("m") or "dim" in suffix else 4)) % 12
                sc = in_w - 0.9 * (total - in_w) + 1.2 * coverage
                if weights.get(root, 0) == 0:
                    sc -= 1.0
                if weights.get(third, 0) == 0:
                    sc -= 0.8
                if bass_pc is not None and bass_pc == root:
                    sc += 1.0
                cands.append((sc, FLAT_NAMES[root] + suffix))
        cands.sort(key=lambda c: -c[0])
        out.append({"measure": number,
                    "bass": FLAT_NAMES[bass_pc] if bass_pc is not None else None,
                    "top": [{"symbol": s, "score": round(sc, 2)} for sc, s in cands[:3]]})
    return {"key": global_key, "parts_analyzed": [part_label(p) for p in parts], "measures": out}


def set_chord_symbols(score, name: str, chords: list[dict]) -> dict:
    """Write chord symbols (MusicXML <harmony>) onto a part at given measures.

    chords: [{"measure": 1, "symbol": "Fm", "offset": 0.0}, ...]
    Symbols use lead-sheet spelling: F, Fm, F7, Fmaj7, Fm7, Fm7b5, Fdim, Fdim7, Faug
    (roots may carry b/#). Replaces any existing symbol at the same spot.
    """
    import re as _re

    from music21 import harmony as m21harmony
    part = find_parts(score, [name])[0]
    measures = {m.number: m for m in part.getElementsByClass(stream.Measure)}
    added = 0
    for spec in chords:
        mnum, sym = spec["measure"], spec["symbol"].strip()
        m = measures.get(mnum)
        if m is None:
            raise ValueError(f"No measure {mnum} in part '{part_label(part)}'")
        match = _re.fullmatch(r"([A-G])(b|#)?(.*)", sym)
        if not match or match.group(3) not in QUALITY_KINDS:
            raise ValueError(f"Bad chord symbol '{sym}'. Qualities: {sorted(QUALITY_KINDS)}")
        root = match.group(1) + {"b": "-", "#": "#", None: ""}[match.group(2)]
        cs = m21harmony.ChordSymbol(root=root, kind=QUALITY_KINDS[match.group(3)])
        off = float(spec.get("offset", 0.0))
        for old in list(m.getElementsByClass(m21harmony.ChordSymbol)):
            if abs(old.offset - off) < 1e-3:
                m.remove(old)
        m.insert(off, cs)
        added += 1
    return {"part": part_label(part), "symbols_added": added}


def info(score) -> dict:
    parts = []
    for i, p in enumerate(score.parts):
        instr = p.getInstrument(returnDefault=False)
        pitches = [pp for n in p.recurse().notes for pp in n.pitches]
        clefs = []
        for c in p.recurse().getElementsByClass(m21clef.Clef):
            label = type(c).__name__.replace("Clef", "").lower()
            if label not in clefs:
                clefs.append(label)
        parts.append({
            "index": i,
            "name": part_label(p),
            "abbreviation": p.partAbbreviation,
            "instrument": instr.instrumentName if instr else None,
            "clefs": clefs,
            "range": [min(pitches).nameWithOctave, max(pitches).nameWithOctave] if pitches else None,
            "measures": len(p.getElementsByClass(stream.Measure)),
            "notes": len(pitches),
        })
    first = score.parts.first()
    time_sigs = [ts.ratioString for ts in first.recurse().getElementsByClass("TimeSignature")] if first else []
    key_sigs = [str(ks) for ks in first.recurse().getElementsByClass("KeySignature")] if first else []
    md = score.metadata
    return {
        "title": (md.title or md.movementName) if md else None,
        "composer": md.composer if md else None,
        "parts": parts,
        "time_signatures": list(dict.fromkeys(time_sigs)),
        "key_signatures": list(dict.fromkeys(key_sigs)),
    }
